apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diabetes-mlops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bittush8789/end-to-end-diabetes-prediction-mlops.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: diabetes-prediction
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
